### ISSUE TITLE
update to rahla 1.0.20 with minio config: bundle rahla:1.0.20 (177)[rahla.smarturl.minio.MinioURLStreamHandlerService(7)] : The activate method has thrown an exception

### ISSUE THREAD

**Issue by JurijKornienko** [dttctcs/rahla#12]
[xml and features.zip](https://github.com/user-attachments/files/16906013/xml.and.features.zip)

features.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<features xmlns="http://karaf.apache.org/xmlns/features/v1.6.0" name="runtime">


  <feature name="runtime" version="1" install="auto">
    <feature>jdbc</feature>
    <feature>pax-jdbc</feature>
    <feature>pax-jdbc-config</feature>
    <feature>pax-jdbc-postgresql</feature>
    <feature>pax-jdbc-h2</feature>
    <feature>pax-jdbc-pool-hikaricp</feature>
    <feature>camel-jsonpath</feature>
    <feature>camel-zip-deflater</feature>
    <feature>camel-jdbc</feature>
    <feature>camel-jetty</feature>
    <feature>camel-openapi-java</feature>
    <feature>camel-http</feature>
    <feature>camel-jetty</feature>
    <feature>camel-jackson</feature>
    <feature>camel-paho</feature>
    <feature>camel-minio</feature>
    <feature>camel-groovy</feature>
    <feature>camel-cron</feature>
    <feature>camel-quartz</feature>
    <feature>camel-csv</feature>

    <bundle>wrap:mvn:com.carrotsearch.thirdparty/simple-xml-safe/2.7.1</bundle>
    <bundle>mvn:org.apache.commons/commons-text/1.10.0</bundle>
    <bundle start-level="80">mvn:org.apache.commons/commons-csv/1.8</bundle>

  </feature>


</features>

```

camel.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<blueprint xmlns="http://www.osgi.org/xmlns/blueprint/v1.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:cm="http://aries.apache.org/blueprint/xmlns/blueprint-cm/v1.1.0"
           xsi:schemaLocation="
         http://www.osgi.org/xmlns/blueprint/v1.0.0 https://www.osgi.org/xmlns/blueprint/v1.0.0/blueprint.xsd
         http://camel.apache.org/schema/blueprint https://camel.apache.org/schema/blueprint/camel-blueprint.xsd
         http://aries.apache.org/blueprint/xmlns/blueprint-cm/v1.1.0 https://aries.apache.org/schemas/blueprint-cm/blueprint-cm-1.1.0.xsd">

    <cm:property-placeholder id="settings.props" persistent-id="settings" update-strategy="reload"/>

    <reference id="beanFactory" interface="rahla.api.GroovyBeanFactory"/>

    <bean id="registry" class="com.codahale.metrics.MetricRegistry" />
    <bean id="routeStats"
        class="org.apache.camel.component.metrics.routepolicy.MetricsRoutePolicyFactory">
        <property name="metricsRegistry" ref="registry" />
    </bean>

    <camelContext useMDCLogging="true"
                  xmlns="http://camel.apache.org/schema/blueprint"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://camel.apache.org/schema/blueprint https://camel.apache.org/schema/blueprint/camel-blueprint-3.20.2.xsd">

        <restConfiguration  component="jetty" bindingMode="off" 
                            contextPath="{{REST_CONTEXT_PATH}}" 
                            port="8183" 
                            host="0.0.0.0" 
                            apiContextRouteId="api-docs" 
                            apiContextPath="api-docs" 
                            enableCORS="true">
        <dataFormatProperty key="prettyPrint" value="true"/>
        <apiProperty key="api.version" value="1.0"/>
        <apiProperty key="api.title" value="Protack data service"/>
        <apiProperty key="api.description" value="This could be your marketing text"/>
        <apiProperty key="api.contact.name" value="datatactics Supoprt"/>
        <apiProperty key="api.contact.email" value="support@datatactics.de"/>
        <apiProperty key="api.contact.url" value="www.datatactics.de"/>
        </restConfiguration>


        <route id="local-testing">
            <from uri="timer://test?fixedRate=true&amp;period=5000000" />
            <log message="FOO" loggingLevel="INFO" />
        </route>



    </camelContext>


</blueprint>

```

A config and connection to minio is required.

Error:

```
06 09:37:43.365 ERROR [rahla.smarturl.minio.MinioURLStreamHandlerService] bundle rahla:1.0.20 (177)[rahla.smarturl.minio.MinioURLStreamHandlerService(7)] : The activate method has thrown an exception
java.lang.NoClassDefFoundError: com/google/common/collect/Multimap
        at io.minio.MinioClient$Builder.<init>(MinioClient.java:2447) ~[?:?]
        at io.minio.MinioClient.builder(MinioClient.java:2439) ~[?:?]
        at rahla.smarturl.minio.MinioURLStreamHandlerService.activate(MinioURLStreamHandlerService.java:72) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:245) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:687) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:531) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317) ~[?:?]
        at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1002) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:975) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:776) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437) ~[?:?]
        at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:671) ~[?:?]
        at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:310) ~[?:?]
        at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:593) ~[?:?]
        at org.apache.felix.scr.impl.Activator.access$200(Activator.java:74) ~[?:?]
        at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:460) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169) ~[?:?]
        at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49) ~[?:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488) ~[osgi.core-8.0.0.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:420) ~[osgi.core-8.0.0.jar:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232) ~[osgi.core-8.0.0.jar:?]
        at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450) ~[osgi.core-8.0.0.jar:?]
        at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915) ~[?:?]
        at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834) ~[?:?]
        at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516) ~[?:?]
        at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4847) ~[?:?]
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2363) ~[?:?]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:1006) ~[?:?]
        at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:992) ~[?:?]
        at org.apache.karaf.features.internal.service.BundleInstallSupportImpl.startBundle(BundleInstallSupportImpl.java:165) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1160) ~[?:?]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:1041) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1069) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:1004) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Multimap not found by wrap_file__rahla_.m2_repository_io_minio_minio_8.4.6_minio-8.4.6.jar [239]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591) ~[?:?]
        at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79) ~[?:?]
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 48 more
```

**Comment by lnnwvr** [comment]
Camel-minio in 3.22.2 seems a bit buggy

instead of feature camel-minio try to install

`        
<bundle>mvn:com.google.guava/guava/30.1.1-jre</bundle>
<bundle>mvn:com.google.guava/failureaccess/1.0.2</bundle>
<bundle>mvn:org.apache.commons/commons-compress/1.26.1</bundle>
<bundle>mvn:commons-io/commons-io/2.13.0</bundle>
<bundle>mvn:commons-codec/commons-codec/1.15</bundle>
<bundle>mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.okhttp/4.10.0_3</bundle>
<bundle>mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.okio/3.8.0_1</bundle>
<bundle>mvn:org.apache.camel/camel-minio/3.22.2</bundle>
<bundle>wrap:mvn:io.minio/minio/8.5.12</bundle>
<bundle>mvn:org.jetbrains.kotlin/kotlin-osgi-bundle/1.7.20</bundle>
`
